# Site settings
title: Melting House - Chocolate Shop and Kitchen, Yorkshire
email: hello@meltinghouse.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Melting House is a chocolate shop and kitchen based in Mirfield, Yorkshire,
  where we make small batches of handmade chocolate. From truffles, bars,
  slabs and shard to Easter eggs, chocolate hampers,
  cakes and baked goods; everything is made by hand here by our small team
  of chocolatiers. You'll also find personalised chocolates and freshly
  handmade treats. Come along to our Mirfield shop to see chocolate
  making in action in the Melting House kitchen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.meltinghouse.co.uk" # the base hostname & protocol for your site
twitter_username: MeltingHouse
facebook_page: MeltingHouseChocolate
github_username:  m0nkmaster
instagram_username: melting_house

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      introduction: "Lovely handmade chocolate from Yorkshire"
